apiVersion: v1
kind: Namespace
metadata:
  name: confluent

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: confluent-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: confluent-operator
subjects:
- kind: ServiceAccount
  name: confluent-operator
  namespace: confluent

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: confluent-operator
  namespace: confluent

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: confluent-operator
  namespace: confluent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: confluent-operator
  template:
    metadata:
      labels:
        app: confluent-operator
    spec:
      serviceAccountName: confluent-operator
      containers:
      - name: confluent-operator
        image: confluentinc/confluent-operator:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 5
