name: Deploy mail-listener
on:
  push:
    paths:
      - 'mail-listener/**'
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Build and Deploy mail-listener
        run: |
          cd mail-listener
          docker build -t mail-listener .
          docker-compose up -d