name: Deploy mail-summarizer
on:
  push:
    paths:
      - 'mail-summarizer/**'
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Build and Deploy mail-summarizer
        run: |
          cd mail-summarizer
          docker build -t mail-summarizer .
          docker-compose up -d